package jp.co.sint.webshop.service.customer;

public final class CustomerAttributeQuery {

  /**
   * default constructor
   */
  private CustomerAttributeQuery() {
  }

  public static final String LOAD_ATTRIBUTE_ALL_QUERY = "SELECT CUSTOMER_ATTRIBUTE_NO, "
      + "CUSTOMER_ATTRIBUTE_NAME, CUSTOMER_ATTRIBUTE_TYPE, DISPLAY_FLG, DISPLAY_ORDER "
      + "FROM CUSTOMER_ATTRIBUTE ORDER BY DISPLAY_ORDER, CUSTOMER_ATTRIBUTE_NO";

  public static final String DELETE_ATTRIBUTE_QUERY = "DELETE FROM CUSTOMER_ATTRIBUTE WHERE CUSTOMER_ATTRIBUTE_NO = ?";

  public static final String LOAD_ATTRIBUTE_CHOICE_ALL_QUERY = "SELECT CUSTOMER_ATTRIBUTE_NO, CUSTOMER_ATTRIBUTE_CHOICES_NO, "
      + "CUSTOMER_ATTRIBUTE_CHOICES, DISPLAY_ORDER FROM CUSTOMER_ATTRIBUTE_CHOICE WHERE CUSTOMER_ATTRIBUTE_NO = ? "
      + "ORDER BY DISPLAY_ORDER, CUSTOMER_ATTRIBUTE_CHOICES_NO";

  public static final String DELETE_ATTRIBUTE_CHOICES_QUERY = "DELETE FROM CUSTOMER_ATTRIBUTE_CHOICE WHERE CUSTOMER_ATTRIBUTE_NO = ?";

  public static final String DELETE_ATTRIBUTE_CUSTOMER_ATTRIBUTE_ANSWER_ALL_QUERY = "DELETE FROM CUSTOMER_ATTRIBUTE_ANSWER "
      + "WHERE CUSTOMER_ATTRIBUTE_NO = ?";

  public static final String LOAD_CUSTOMER_ATTRIBUTE_ANSWER_ALL_QUERY = "SELECT CUSTOMER_ATTRIBUTE_NO, "
      + "CUSTOMER_ATTRIBUTE_CHOICES_NO, CUSTOMER_CODE FROM CUSTOMER_ATTRIBUTE_ANSWER "
      + "WHERE CUSTOMER_ATTRIBUTE_NO = ? AND CUSTOMER_CODE = ?";

  public static final String LOAD_CUSTOMER_ATTRIBUTE_ANSWER_CUSTOMER_QUERY = "SELECT CUSTOMER_CODE, CUSTOMER_ATTRIBUTE_NO, "
      + "CUSTOMER_ATTRIBUTE_CHOICES_NO, ORM_ROWID, CREATED_USER, CREATED_DATETIME, UPDATED_USER, UPDATED_DATETIME "
      + "FROM CUSTOMER_ATTRIBUTE_ANSWER WHERE CUSTOMER_CODE = ?";

  public static final String DELETE_ATTRIBUTE_CHOICE_QUERY = "DELETE FROM CUSTOMER_ATTRIBUTE_CHOICE WHERE CUSTOMER_ATTRIBUTE_NO = ? "
      + "AND CUSTOMER_ATTRIBUTE_CHOICES_NO = ?";

}
