package jp.co.sint.webshop.service.customer;

import jp.co.sint.webshop.data.DatabaseUtil;
import jp.co.sint.webshop.data.dto.CustomerGroupCampaign;
import jp.co.sint.webshop.data.dto.NewCouponRuleUseInfo;

public final class CustomerGroupQuery {

  /**
   * default constructor
   */
  private CustomerGroupQuery() {
  }

  public static final String LOAD_ALL_QUERY = "SELECT A.CUSTOMER_GROUP_CODE, A.CUSTOMER_GROUP_NAME, "
      + "A.CUSTOMER_GROUP_POINT_RATE, A.UPDATED_DATETIME, " + "COALESCE(B.MEMBER_SHIP,0) AS MEMBER_SHIP, "
      // 20120517 shen add start
      + "A.CUSTOMER_GROUP_NAME_EN, A.CUSTOMER_GROUP_NAME_JP "
      // 20120517 shen add end
      + "FROM CUSTOMER_GROUP A LEFT OUTER JOIN " + "(SELECT CUSTOMER_GROUP_CODE, COUNT(CUSTOMER_GROUP_CODE) AS MEMBER_SHIP  "
      + "FROM CUSTOMER WHERE WITHDRAWAL_DATE IS NULL GROUP BY CUSTOMER_GROUP_CODE ) B "
      + "ON A.CUSTOMER_GROUP_CODE = B.CUSTOMER_GROUP_CODE " + "ORDER BY CUSTOMER_GROUP_CODE";

  public static final String LOAD_QUERY = "SELECT A.CUSTOMER_GROUP_CODE," + "A.CUSTOMER_GROUP_NAME,A.CUSTOMER_GROUP_POINT_RATE,"
      + "A.ORM_ROWID,A.CREATED_USER,A.CREATED_DATETIME,A.UPDATED_USER,A.UPDATED_DATETIME, "
      // 20120515 shen add start
      + "A.CUSTOMER_GROUP_NAME_EN, A.CUSTOMER_GROUP_NAME_JP, "
      // 20120515 shen add end
      + "COALESCE(B.MEMBER_SHIP,0) AS MEMBER_SHIP " + "FROM CUSTOMER_GROUP A LEFT OUTER JOIN "
      + "(SELECT CUSTOMER_GROUP_CODE, COUNT(CUSTOMER_GROUP_CODE) AS MEMBER_SHIP  "
      + "FROM CUSTOMER WHERE WITHDRAWAL_DATE IS NULL GROUP BY CUSTOMER_GROUP_CODE ) B "
      + "ON A.CUSTOMER_GROUP_CODE = B.CUSTOMER_GROUP_CODE WHERE A.CUSTOMER_GROUP_CODE = ? " + "ORDER BY CUSTOMER_GROUP_CODE";

  // 20111223 shen add start
  public static final String LOAD_CUSTOMER_GROUP_CAMPAIGN_BY_GROUP_CODE_QUERY = DatabaseUtil.getSelectAllQuery(CustomerGroupCampaign.class)
      + " WHERE NOW() BETWEEN CAMPAIGN_START_DATETIME AND CAMPAIGN_END_DATETIME AND SHOP_CODE = ? AND (CUSTOMER_GROUP_CODE = ? OR CUSTOMER_GROUP_CODE IS NULL)"
      + " ORDER BY CAMPAIGN_START_DATETIME DESC, CAMPAIGN_END_DATETIME DESC";
  // 20111223 shen add end
}
