package jp.co.sint.webshop.service.order;

public final class JdServiceQuery {

  /**
   * 出荷Noがもつ出荷明細(TMALL_SHIPPING_DETAIL)を全件取得するSQL <BR>
   * [0]出荷No SHIPPING_NO
   */
  public static final String JD_SHIPPING_DETAIL_LIST_QUERY = "SELECT * FROM JD_SHIPPING_DETAIL "
      + "WHERE SHIPPING_NO = ? ORDER BY SHIPPING_DETAIL_NO ASC ";

  /**
   * 京东api未发货成功的shippingHeader集合 <BR>
   * [0]支付区分
   */
  public static final String JD_SHIPPING_HEADER_LIST_GET = "SELECT TSH.* FROM JD_SHIPPING_HEADER TSH "
  + " INNER JOIN JD_ORDER_HEADER TOH ON TOH.ORDER_NO = TSH.ORDER_NO "
  + " WHERE (JD_SHIPPING_FLG <> 1 OR JD_SHIPPING_FLG IS NULL) " + " AND (RETURN_ITEM_TYPE <> 1 OR RETURN_ITEM_TYPE IS NULL) "
  + " AND SHIPPING_STATUS = 3 and (CHILD_ORDER_NO IS NULL OR IS_PART = 'SH') "
  + " ORDER BY  TSH.ORDER_NO ASC ";
  
  // 取得订单商品的code, name
  public static final String JD_ORDER_DETAIL_COMMODITY_LIST = "SELECT COMMODITY_CODE, COMMODITY_NAME FROM JD_ORDER_DETAIL "
    + "WHERE ORDER_NO = ? AND SHOP_CODE = ?";
  

  //取得京东拆分的所有项
  public static final String JD_ORDER_PAYMENT_GETS="SELECT JOH.ORDER_PAYMENT,JSH.ORDER_NO,CHILD_ORDER_NO,JSH.SHIPPING_STATUS FROM JD_ORDER_HEADER JOH,JD_SHIPPING_HEADER JSH"
    +" WHERE JOH.ORDER_NO=JSH.ORDER_NO AND JSH.RETURN_ITEM_TYPE=0 AND JOH.ORDER_NO IN (SELECT DISTINCT ORDER_NO FROM JD_SHIPPING_HEADER"
    +" WHERE (SHIPPING_STATUS='2' OR SHIPPING_STATUS='3') AND RETURN_ITEM_TYPE=0 AND CHILD_ORDER_NO IS NOT NULL)";
}
