package jp.co.sint.webshop.service.shop;

public final class ShopDeleteQuery {

  private static final long serialVersionUID = 1L;

  private ShopDeleteQuery() {
  }

  public static String[] getDeleteQuery() {
    final String[] query = { "DELETE FROM ARRIVAL_GOODS WHERE SHOP_CODE = ?",
        "DELETE FROM POPULAR_RANKING_DETAIL WHERE SHOP_CODE = ?",
        "DELETE FROM REVIEW_POST WHERE SHOP_CODE = ?",
        "DELETE FROM REVIEW_SUMMARY WHERE SHOP_CODE = ?", "DELETE FROM STOCK WHERE SHOP_CODE = ?",
        "DELETE FROM STOCK_IO_DETAIL WHERE SHOP_CODE = ?",
        "DELETE FROM CAMPAIGN WHERE SHOP_CODE = ?",
        "DELETE FROM CAMPAIGN_COMMODITY WHERE SHOP_CODE = ?",
        "DELETE FROM CATEGORY_ATTRIBUTE_VALUE WHERE SHOP_CODE = ?",
        "DELETE FROM COMMODITY_HEADER WHERE SHOP_CODE = ?",
        "DELETE FROM COMMODITY_DETAIL WHERE SHOP_CODE = ?", "DELETE FROM GIFT WHERE SHOP_CODE = ?",
        "DELETE FROM GIFT_COMMODITY WHERE SHOP_CODE = ?",
        "DELETE FROM RELATED_COMMODITY_A WHERE SHOP_CODE = ?",
        "DELETE FROM RELATED_COMMODITY_B WHERE SHOP_CODE = ?",
        "DELETE FROM STOCK_STATUS WHERE SHOP_CODE = ?", "DELETE FROM TAG WHERE SHOP_CODE = ?",
        "DELETE FROM TAG_COMMODITY WHERE SHOP_CODE = ?",
        "DELETE FROM ORDER_DETAIL WHERE SHOP_CODE = ?",
        "DELETE FROM ORDER_HEADER WHERE SHOP_CODE = ?",
        "DELETE FROM SHIPPING_DETAIL WHERE SHOP_CODE = ?",
        "DELETE FROM SHIPPING_HEADER WHERE SHOP_CODE = ?", "DELETE FROM BANK WHERE SHOP_CODE = ?",
        "DELETE FROM COMMISSION WHERE SHOP_CODE = ?",
        "DELETE FROM DELIVERY_APPOINTED_TIME WHERE SHOP_CODE = ?",
        "DELETE FROM DELIVERY_TYPE WHERE SHOP_CODE = ?", "DELETE FROM HOLIDAY WHERE SHOP_CODE = ?",
        "DELETE FROM MAIL_TEMPLATE_HEADER WHERE SHOP_CODE = ?",
        "DELETE FROM MAIL_TEMPLATE_DETAIL WHERE SHOP_CODE = ?",
        "DELETE FROM REGION_BLOCK_LOCATION WHERE SHOP_CODE = ?",
        "DELETE FROM REGION_BLOCK WHERE SHOP_CODE = ?",
        "DELETE FROM SHIPPING_CHARGE WHERE SHOP_CODE = ?", "DELETE FROM SHOP WHERE SHOP_CODE = ?",
        "DELETE FROM USER_ACCOUNT WHERE SHOP_CODE = ?",
        "DELETE FROM USER_ACCESS_LOG WHERE SHOP_CODE = ?",
        "DELETE FROM FAVORITE_COMMODITY WHERE SHOP_CODE = ?",
        "DELETE FROM RECOMMENDED_COMMODITY WHERE SHOP_CODE = ?",
        "DELETE FROM COMMODITY_ACCESS_LOG WHERE SHOP_CODE = ?"
        // 10.1.2 10098 追加 ここから
        , "DELETE FROM PAYMENT_METHOD WHERE SHOP_CODE = ?"
    // 10.1.2 10098 追加 ここまで
    };
    return query;
  }

  // soukai add 2011/12/21 ob shb begin
  public static String[] getDeliveryRegionDeleteQuery() {
    final String[] query = {
        "DELETE FROM DELIVERY_REGION WHERE SHOP_CODE = ? AND DELIVERY_COMPANY_NO = ? AND PREFECTURE_CODE = ?",
        "DELETE FROM DELIVERY_RELATED_INFO WHERE SHOP_CODE = ? AND DELIVERY_COMPANY_NO = ? AND PREFECTURE_CODE = ?"
    };

    return query;
  }
  // soukai add 2011/12/21 ob shb end
  
  public static String[] getDeliveryRegionDeleteQueryJd() {
    final String[] query = {
        "DELETE FROM JD_DELIVERY_REGION WHERE SHOP_CODE = ? AND DELIVERY_COMPANY_NO = ? AND PREFECTURE_CODE = ?",
        "DELETE FROM JD_DELIVERY_RELATED_INFO WHERE SHOP_CODE = ? AND DELIVERY_COMPANY_NO = ? AND PREFECTURE_CODE = ?"
    };

    return query;
  }
  
  public static String[] getDeliveryRegionDeleteQueryTmall() {
    final String[] query = {
        "DELETE FROM TMALL_DELIVERY_REGION WHERE SHOP_CODE = ? AND DELIVERY_COMPANY_NO = ? AND PREFECTURE_CODE = ?",
        "DELETE FROM TMALL_DELIVERY_RELATED_INFO WHERE SHOP_CODE = ? AND DELIVERY_COMPANY_NO = ? AND PREFECTURE_CODE = ?"
    };

    return query;
  }

}
